### ISSUE TITLE
I'm getting a NoClassDefFoundError for the retrofit.RestAdapter in the CDA client only on android api 19(4.4.4) on a Huawei Y635-l01.

### ISSUE THREAD

**Issue by eirini91** [contentful/vault#116]
This issue in not happening in any other device

These are the related dependencies. As you can see i'm using retrofit in the app as well:
   apt 'com.contentful.vault:compiler:2.0.0'
    compile'com.contentful.vault:core:2.0.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0'
    compile('com.squareup.retrofit2:adapter-rxjava:2.0.0') {
        exclude module: 'rxjava'
        exclude module: 'rxandroid'
    }

I'm building the CDAClient in the application class' onCreate().

Fatal Exception: java.lang.NoClassDefFoundError: retrofit.RestAdapter$Builder
       at com.contentful.java.cda.CDAClient.createService(CDAClient.java:54)
       at com.contentful.java.cda.CDAClient.<init>(CDAClient.java:38)
       at com.contentful.java.cda.CDAClient.<init>(CDAClient.java:23)
       at com.contentful.java.cda.CDAClient$Builder.build(CDAClient.java:265)
       at uk.co.activityhunter.activityhunter.util.ProjectUtils.setCDAClient(ProjectUtils.java:105)
       at uk.co.activityhunter.activityhunter.application.AHApp.onCreate(AHApp.java:26)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4632)
       at android.app.ActivityThread.access$1800(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5336)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by mariobodemann** [comment]
Hello,

are you using proguard? And if so which proguard configuration file did you use?

Greetings,
Mario

**Comment by mariobodemann** [comment]
Hey @eirini91,

did my suggestion help in anyway, or do you need some more assitance?

**Comment by eirini91** [comment]
Hi Mario,

I sorted this before you replied. No it wasn't proguard after all. What
fixed it was adding  MultiDex.install(this);  in the application class even
though I had multiDexEnabled true in the gradle.. I'm not sure why this was
an issue only on that particular device.

Thank you for trying to help.

Regards,
Eirini

**Comment by mariobodemann** [comment]
Hey @eirini91,

thank you for comming back on the issue, I'm happy to see it fixed and will close this thread now.

If you need any other assistance, please feel free to reopen, or create a new issue ...
