### ISSUE TITLE
Vault catches StackOverflow unmanagable loop with circular references

### ISSUE THREAD

**Issue by kzotin** [contentful/vault#127]
Added comments to similar issue: https://github.com/contentful/vault/issues/103

**Comment by kzotin** [comment]
cc @mariobodemann @tomxor

**Comment by kzotin** [comment]
Hi,
Do you any thoughts on the issue?
Circular 1-to-many dependencies are not working. For now, we've reengineered some parts with duct tape :) 

Copy of my comment from the similar issue:
Our model is fairly simple. We have Practices and Guides with 1--N relationship. 
Practice has `List<Guide> guides`, Guide has `Practice practice`.

Surprisingly, it works for some content items, and don't for others.
We're querying in following way:
```
.observe(Guide.class)
.where(Guide$Fields.REMOTE_ID + " = ?", guideId)
.all()
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
.subscribe(callback, throwable -> Logger.d("error:" + throwable));
```

Error stacktrace:
```
08-02 00:43:01.869 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.agilityscales.app.dev, PID: 5496
                                     java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                         at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5438)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                      Caused by: java.lang.StackOverflowError: stack size 1037KB
                                         at com.agilityscales.content.Practice.<init>(Practice.java:11)
                                         at com.agilityscales.content.Practice$$ModelHelper.fromCursor(Practice$$ModelHelper.java:46)
                                         at com.agilityscales.content.Practice$$ModelHelper.fromCursor(Practice$$ModelHelper.java:11)
                                         at com.contentful.vault.SqliteHelper.fromCursor(SqliteHelper.java:145)
                                         at com.contentful.vault.QueryResolver.all(QueryResolver.java:51)
                                         at com.contentful.vault.FetchQuery.resolveAll(FetchQuery.java:30)
                                         at com.contentful.vault.FetchQuery.resolveFirst(FetchQuery.java:37)
                                         at com.contentful.vault.LinkResolver.resourceForLink(LinkResolver.java:197)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:96)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                     	at com.conten

```

**Comment by kzotin** [comment]
Model & database dump can be found here:
https://drive.google.com/drive/u/0/folders/0BzDAFAs4761_bDYwVy04eF95V2s

Please let me know when you download them, I'll stop sharing.

**Comment by kzotin** [comment]
hi @mariobodemann,
Got any thoughts regarding this issue?

**Comment by mariobodemann** [comment]
Hey, 

I will take a look ...

**Comment by mariobodemann** [comment]
The issue, is when a linked reference is created, it tries to resolve its references before putting itselve into the cache. This is a problem for backlinked entries, because they will try and look for the intermediate object in the cache, not find it and are trying to recreate it, so the circle starts over again. 

The solution is to put the items in the cache first, resolve their links, updating them on the cached object. So to move one line two lines up ... ;)

@kzotin if you have the chance, would you mind checking if this is a solution for you?

**Comment by kzotin** [comment]
Thank you for the fix. Can test it in ~2 weeks timeframe. 
We've updated the content model to get rid of such links.

**Comment by mariobodemann** [comment]
Okay, that is great to hear. 

I will have this fix in with the next version then, taking care of the newest dependencies...

Thanks for the feedback, and you are welcome to give more feedback ...

Greetings,
Mario
