### ISSUE TITLE
VaultDatabaseExporter Broken in 3.2.3

### ISSUE THREAD

**Issue by Crylic** [contentful/vault#158]
Pull request #157 broke the VaultDatabaseExporter since the environment ID has not been set and no functionality is exposed to actually set the environment ID in the exporter.

Would like to see that VaultDatabaseExporter gets extended to be able to set the environment ID.

`java.lang.NullPointerException: Environment ID must not be null.
	at com.contentful.java.cda.Util.checkNotNull(Util.java:26)
	at com.contentful.java.cda.CDAClient.validate(CDAClient.java:96)
	at com.contentful.java.cda.CDAClient.<init>(CDAClient.java:81)
	at com.contentful.java.cda.CDAClient$Builder.build(CDAClient.java:770)
	at com.contentful.vault.SyncConfig.<init>(SyncConfig.java:49)
	at com.contentful.vault.SyncConfig$Builder.build(SyncConfig.java:124)
	at com.contentful.vault.VaultDatabaseExporter.export(VaultDatabaseExporter.java:44)
	`

**Comment by rafalniski** [comment]
Hey @Crylic ,

I created a small PR here - https://github.com/contentful/vault/pull/161 - would you mind take a look if that resolves your problem?

**Comment by rafalniski** [comment]
This should be fixed in `3.2.5`
